---
deployment:
  tasks:
    # Set the deployment path to the ReactDev subdirectory
    - export DEPLOYPATH=/home/domkzn/public_html/ReactDev

    # Deploy Frontend into the ReactDev directory
    - /bin/mkdir -p $DEPLOYPATH # Ensure ReactDev directory exists
    - /bin/cp -R Hosting-Frontend/dist/. $DEPLOYPATH/ # Use relative source path

    # Deploy Backend Dashboard into React/admin-dashboard/
    - /bin/mkdir -p $DEPLOYPATH/admin-dashboard # Create admin-dashboard within React
    - /bin/cp -R Hosting-backend/dist/. $DEPLOYPATH/admin-dashboard/ # Use relative source path

    # Deploy PHP API into React/php-api/
    - /bin/mkdir -p $DEPLOYPATH/php-api # Create php-api within React
    - /bin/cp -R php-api/. $DEPLOYPATH/php-api/ # Use relative source path
