# cPanel Deployment Script for HKZN Project (Node.js Frontend + PHP API)
# ======================================================================
# This script deploys the Node.js frontend application to a dedicated
# directory managed by cPanel's Node.js Selector and deploys the PHP API
# to the public web root.

deployment:
  tasks:
    # Exit immediately if a command exits with a non-zero status.
    - set -e

    # --- Configuration ---
    # Define the target directory for the Node.js application files.
    # This should match the 'Application root' configured in cPanel's Node.js Selector.
    - export APP_PATH=/home/domkzn/hkznapp

    # Define the web server's document root for the PHP API.
    - export WEB_ROOT=/home/domkzn/public_html

    # Define the path to the PHP API within the web root.
    - export API_PATH=$WEB_ROOT/api

    # Git repository details
    - export REPO_URL=https://github.com/WimpyvL/HKZN.git
    - export BRANCH=production # Or the branch you want to deploy

    # --- Deployment Steps ---
    - echo "--- Starting HKZN Deployment ---"

    # 1. Deploy/Update Node.js Application Source Code
    - echo "Deploying Node.js app source to $APP_PATH..."
    # Check if the application directory exists and contains a Git repo.
    # If yes, pull the latest changes. If no, clone the repository.
    - if [ -d "$APP_PATH/.git" ]; then echo "Updating existing repository..."; cd $APP_PATH && git checkout $BRANCH && git pull origin $BRANCH; else echo "Cloning new repository..."; git clone --branch $BRANCH $REPO_URL $APP_PATH; fi
    - cd $APP_PATH # Ensure we are in the main app directory

    # 2. Build Frontend Application
    - echo "Building frontend application..."
    - cd HKZN-App/frontend # Navigate to the frontend directory
    - echo "Installing frontend dependencies (npm install)..."
    - npm install # Install dependencies defined in frontend/package.json
    - echo "Building frontend assets (npm run build)..."
    - npm run build # Run the build script defined in frontend/package.json
    # The built assets will be in HKZN-App/frontend/dist/
    # The server.js script will serve these assets.
    - echo "Frontend build complete. Ready for Node.js manager."

    # 3. Deploy PHP API Files
    - echo "Deploying PHP API to $API_PATH..."
    # Ensure the target API directory exists in the web root.
    - /bin/mkdir -p $API_PATH
    # Copy the API files from the cloned repository to the web root API path.
    # Using -a to preserve attributes and recursively copy.
    - /bin/cp -a $APP_PATH/HKZN-App/api/. $API_PATH/
    - echo "PHP API deployment complete."

    # --- Finalization ---
    - echo "--- HKZN Deployment Script Finished ---"
    # Note: After this script runs, you need to ensure the Node.js application
    # is (re)started via the cPanel Node.js Selector interface.
