---
deployment:
  tasks:
    # Exit immediately if a command exits with a non-zero status.
    - set -e
    # Define the deployment path on the server
    - export DEPLOYPATH=/home/domkzn/public_html/React

    # Navigate to the frontend directory, install dependencies, and build
    - cd HKZN-App/frontend && npm install && npx vite build && cd ../..

    # Prepare the deployment directory on the server (optional: remove previous content)
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/mkdir -p $DEPLOYPATH

    # Deploy Frontend (copy built assets from dist)
    - /bin/cp -R HKZN-App/frontend/dist/. $DEPLOYPATH/

    # Deploy PHP API into the api subdirectory
    - /bin/mkdir -p $DEPLOYPATH/api
    - /bin/cp -R HKZN-App/api/. $DEPLOYPATH/api/
