---
deployment:
  tasks:
    # Exit immediately if a command exits with a non-zero status.
    - set -e
    # Define the deployment path on the server
    - export DEPLOYPATH=/home/domkzn/public_html/ReactDev

    # --- Build Frontend ---
    - echo "--- Navigating to frontend ---"
    - cd HKZN-App/frontend
    - echo "--- Starting npm install ---"
    - npm install
    - echo "--- Finished npm install ---"
    - echo "--- Starting vite build ---"
    - npx vite build
    - echo "--- Finished vite build ---"
    - cd ../.. # Go back to the repository root
    - echo "--- Listing dist directory contents after build ---"
    - ls -la HKZN-App/frontend/dist/
    - echo "--- End listing dist directory ---"

    # --- Prepare Deployment Directory ---
    - echo "--- Preparing deployment directory: $DEPLOYPATH ---"
    # Ensure the main deployment directory exists
    - /bin/mkdir -p $DEPLOYPATH
    # Optionally clear previous frontend/API content if needed (be careful with this)
    # - /bin/rm -rf $DEPLOYPATH/* # Uncomment cautiously if you want a clean deploy each time

    # --- Deploy Frontend ---
    - echo "--- Deploying Frontend to $DEPLOYPATH ---"
    # Clear only previous frontend assets, leave API untouched if rm -rf * was not used above
    - /bin/rm -rf $DEPLOYPATH/assets $DEPLOYPATH/index.html $DEPLOYPATH/.htaccess $DEPLOYPATH/favicon.ico # Add other specific frontend files/dirs if needed
    - /bin/cp -R HKZN-App/frontend/dist/. $DEPLOYPATH/
    # Explicitly copy .htaccess again just in case cp -R didn't overwrite correctly or if it wasn't in dist
    - '[ -f HKZN-App/frontend/dist/.htaccess ] && /bin/cp HKZN-App/frontend/dist/.htaccess $DEPLOYPATH/.htaccess || echo ".htaccess not found in dist, skipping explicit copy."'

    # --- Deploy PHP API ---
    - echo "--- Deploying PHP API to $DEPLOYPATH/api ---"
    - /bin/mkdir -p $DEPLOYPATH/api # Ensure the api subdirectory exists
    # Clear previous API files before copying new ones
    - /bin/rm -rf $DEPLOYPATH/api/*
    - /bin/cp -R HKZN-App/api/. $DEPLOYPATH/api/
    - echo "--- Deployment script finished ---"
