---
deployment:
  tasks:
    # Exit immediately if a command exits with a non-zero status.
    - set -e
    # Define the deployment path on the server
    - export DEPLOYPATH=/home/domkzn/public_html/ReactDev

    # --- FRONTEND BUILD STEPS COMMENTED OUT FOR TESTING ---
    # - echo "--- Navigating to frontend ---"
    # - cd HKZN-App/frontend && npm install && npx vite build && cd ../..
    # - echo "--- Listing dist directory contents after build ---"
    # - ls -la HKZN-App/frontend/dist/
    # - echo "--- End listing dist directory ---"
    # --- END OF COMMENTED OUT SECTION ---

    # Prepare the deployment directory on the server (optional: remove previous content)
    - echo "--- Preparing deployment directory (API only) ---"
    - /bin/rm -rf $DEPLOYPATH/* # Note: This will clear the directory
    - /bin/mkdir -p $DEPLOYPATH

    # --- FRONTEND DEPLOYMENT COMMENTED OUT ---
    # - echo "--- Deploying Frontend (Skipped) ---"
    # - /bin/cp -R HKZN-App/frontend/dist/. $DEPLOYPATH/
    # - '[ -f HKZN-App/frontend/dist/.htaccess ] && /bin/cp HKZN-App/frontend/dist/.htaccess $DEPLOYPATH/.htaccess || echo ".htaccess not found in dist, skipping explicit copy."'
    # --- END OF COMMENTED OUT SECTION ---

    # Deploy PHP API into the api subdirectory
    - echo "--- Deploying PHP API ---"
    - /bin/mkdir -p $DEPLOYPATH/api
    - /bin/cp -R HKZN-App/api/. $DEPLOYPATH/api/
    - echo "--- API Deployment Attempt Finished ---"
