---
deployment:
  tasks:
    # Set the deployment path to the ReactDev subdirectory
    - export DEPLOYPATH=/home/domkzn/ReactDev

    # Deploy Frontend into the ReactDev directory
    - /bin/mkdir -p $DEPLOYPATH # Ensure ReactDev directory exists
    - /bin/cp -R /home/domkzn/ReactDev/Hosting-Frontend/dist/. $DEPLOYPATH/

    # Deploy Backend Dashboard into React/admin-dashboard/
    - /bin/mkdir -p $DEPLOYPATH/admin-dashboard # Create admin-dashboard within React
    - /bin/cp -R /home/domkzn/ReactDev/Hosting-backend/dist/. $DEPLOYPATH/admin-dashboard/

    # Deploy PHP API into React/php-api/
    - /bin/mkdir -p $DEPLOYPATH/php-api # Create php-api within React
    - /bin/cp -R /home/domkzn/ReactDev/php-api/. $DEPLOYPATH/php-api/
