---
deployment:
  tasks:
    # Exit immediately if a command exits with a non-zero status.
    - set -e
    # Define the deployment path on the server
    - export DEPLOYPATH=/home/domkzn/public_html/ReactDev

    # Navigate to the frontend directory, install dependencies, and build
    - cd HKZN-App/frontend && npm install && npx vite build && cd ../..
    # List dist contents after build for debugging
    - echo "--- Listing dist directory contents after build ---"
    - ls -la HKZN-App/frontend/dist/
    - echo "--- End listing dist directory ---"

    # Prepare the deployment directory on the server (optional: remove previous content)
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/mkdir -p $DEPLOYPATH

    # Deploy Frontend (copy built assets from dist)
    - /bin/cp -R HKZN-App/frontend/dist/. $DEPLOYPATH/

    # Explicitly copy .htaccess if it exists in dist, just to be sure
    - '[ -f HKZN-App/frontend/dist/.htaccess ] && /bin/cp HKZN-App/frontend/dist/.htaccess $DEPLOYPATH/.htaccess || echo ".htaccess not found in dist, skipping explicit copy."'

    # Deploy PHP API into the api subdirectory
    - /bin/mkdir -p $DEPLOYPATH/api
    - /bin/cp -R HKZN-App/api/. $DEPLOYPATH/api/
