---
deployment:
  tasks:
    # Set the deployment path to the React subdirectory
    - export DEPLOYPATH=/home/domkzn/public_html/React

    # Deploy Frontend (built assets) into the React directory
    - /bin/mkdir -p $DEPLOYPATH # Ensure React directory exists
    - /bin/cp -R HKZN-App/frontend/dist/. $DEPLOYPATH/ # Copy contents of dist

    # Deploy PHP API into React/api/
    - /bin/mkdir -p $DEPLOYPATH/api # Ensure api directory exists within React
    - /bin/cp -R HKZN-App/api/. $DEPLOYPATH/api/ # Copy contents of api
