# Netlify build configuration for the Frontend

[build]
  # Base directory for the merged frontend app
  base = "HKZN-App/frontend"
  # Build command (defined in frontend's package.json)
  command = "npm run build"
  # Directory containing the built assets relative to the repository root
  publish = "HKZN-App/frontend/dist"

# Redirect rule for Single Page Applications (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
